server:
  port: 8081

api:
  path:
    global-prefix: /api

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:productsdb}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1qaz2wsx}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ